### ISSUE TITLE
Request: SRB2 Kart

### ISSUE THREAD

**Issue by joelou1** [mazmazz/SRB2#34]
Yeah, I know it's a bit selfish for asking this, but would it be possible to have SRB2 Kart as well? Since it doesn't count as a mod, it's not bootable through "mods". My reasoning behind this is that a friend and I tried your online version of SRB2 (And enjoyed it since he can't have it installed due to having a chromebook) and I wondered if it was possible to have the Kart version.

Eitherway, great job pulling this together, much appreciated!

**Comment by mazmazz** [comment]
Thanks for your comment. It would be a very big commitment to support Kart, and I don't plan on doing so. You'll have to ask Kart Krew if they want to pursue that work themselves. Enjoy SRB2!
